wget http://vimcolorschemetest.googlecode.com/svn/html/256-jungle-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/256-jungle-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/256-jungle-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/256-jungle-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/256-jungle-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/3dglasses-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/3dglasses-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/3dglasses-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/3dglasses-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/3dglasses-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Black-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Black-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Black-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Black-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Black-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BlackSea-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BlackSea-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BlackSea-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BlackSea-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BlackSea-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Blue2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Blue2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Blue2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Blue2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Blue2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BusyBee-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BusyBee-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BusyBee-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BusyBee-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/BusyBee-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolateLiquor-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolateLiquor-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolateLiquor-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolateLiquor-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolateLiquor-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolatePapaya-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolatePapaya-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolatePapaya-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolatePapaya-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ChocolatePapaya-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dark2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DarkDefault-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DarkDefault-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DarkDefault-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DarkDefault-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DarkDefault-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DevC++-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DevC++-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DevC++-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DevC++-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DevC++-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Dim2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimBlue-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimBlue-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimBlue-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimBlue-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimBlue-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreen-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreen-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreen-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreen-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreen-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreens-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreens-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreens-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreens-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGreens-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGrey-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGrey-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGrey-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGrey-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimGrey-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimRed-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimRed-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimRed-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimRed-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimRed-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimSlate-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimSlate-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimSlate-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimSlate-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/DimSlate-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Green-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Green-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Green-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Green-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Green-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Light-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Light-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Light-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Light-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Light-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefault-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefault-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefault-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefault-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefault-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefaultGrey-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefaultGrey-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefaultGrey-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefaultGrey-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightDefaultGrey-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightTan-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightTan-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightTan-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightTan-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightTan-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightYellow-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightYellow-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightYellow-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightYellow-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/LightYellow-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/MountainDew-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/MountainDew-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/MountainDew-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/MountainDew-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/MountainDew-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/PapayaWhip-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/PapayaWhip-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/PapayaWhip-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/PapayaWhip-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/PapayaWhip-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Red-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Red-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Red-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Red-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Red-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Slate-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Slate-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Slate-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Slate-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/Slate-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/White2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/White2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/White2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/White2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/White2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adam-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adam-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adam-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adam-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adam-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adaryn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adaryn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adaryn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adaryn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adaryn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adobe-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adobe-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adobe-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adobe-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adobe-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adrian-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adrian-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adrian-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adrian-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/adrian-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/advantage-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/advantage-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/advantage-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/advantage-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/advantage-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/af-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/af-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/af-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/af-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/af-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aiseered-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aiseered-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aiseered-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aiseered-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aiseered-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/anotherdark-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/anotherdark-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/anotherdark-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/anotherdark-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/anotherdark-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ansi_blows-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ansi_blows-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ansi_blows-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ansi_blows-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ansi_blows-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aqua-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aqua-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aqua-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aqua-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/aqua-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ashen-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ashen-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ashen-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ashen-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/ashen-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian_blood-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian_blood-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian_blood-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian_blood-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmanian_blood-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asmdev2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/astronaut-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/astronaut-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/astronaut-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/astronaut-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/astronaut-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asu1dark-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asu1dark-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asu1dark-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asu1dark-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/asu1dark-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/automation-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/automation-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/automation-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/automation-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/automation-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumn2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumnleaf-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumnleaf-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumnleaf-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumnleaf-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/autumnleaf-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bandit-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bandit-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bandit-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bandit-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bandit-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/basic-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/basic-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/basic-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/basic-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/basic-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bayQua-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bayQua-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bayQua-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bayQua-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bayQua-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/baycomb-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/baycomb-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/baycomb-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/baycomb-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/baycomb-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beachcomber-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beachcomber-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beachcomber-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beachcomber-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beachcomber-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beauty256-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beauty256-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beauty256-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beauty256-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/beauty256-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bensday-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bensday-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bensday-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bensday-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bensday-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/billw-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/billw-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/billw-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/billw-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/billw-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/biogoo-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/biogoo-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/biogoo-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/biogoo-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/biogoo-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/black_angus-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/black_angus-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/black_angus-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/black_angus-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/black_angus-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackbeauty-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackbeauty-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackbeauty-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackbeauty-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackbeauty-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackboard-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackboard-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackboard-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackboard-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackboard-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackdust-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackdust-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackdust-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackdust-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blackdust-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blacklight-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blacklight-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blacklight-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blacklight-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blacklight-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blink-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blink-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blink-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blink-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blink-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blue-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blue-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blue-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blue-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blue-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluegreen-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluegreen-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluegreen-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluegreen-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluegreen-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blueprint-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blueprint-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blueprint-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blueprint-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blueprint-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluez-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluez-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluez-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluez-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bluez-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blugrine-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blugrine-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blugrine-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blugrine-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/blugrine-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bmichaelsen-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bmichaelsen-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bmichaelsen-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bmichaelsen-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bmichaelsen-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bog-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bog-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bog-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bog-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bog-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/borland-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/borland-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/borland-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/borland-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/borland-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/breeze-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/breeze-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/breeze-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/breeze-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/breeze-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brookstream-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brookstream-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brookstream-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brookstream-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brookstream-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brown-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brown-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brown-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brown-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/brown-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/buttercream-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/buttercream-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/buttercream-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/buttercream-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/buttercream-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bw-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bw-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bw-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bw-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/bw-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c16gui-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c16gui-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c16gui-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c16gui-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/c16gui-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-dark-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-dark-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-dark-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-dark-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-dark-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-light-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-light-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-light-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-light-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/calmar256-light-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/camo-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/camo-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/camo-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/camo-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/camo-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/campfire-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/campfire-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/campfire-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/campfire-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/campfire-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candy-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candy-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candy-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candy-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candy-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candycode-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candycode-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candycode-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candycode-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/candycode-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/caramel-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/caramel-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/caramel-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/caramel-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/caramel-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carrot-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carrot-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carrot-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carrot-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carrot-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwood-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwood-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwood-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwood-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwood-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwoodcool-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwoodcool-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwoodcool-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwoodcool-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/carvedwoodcool-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charged-256-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charged-256-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charged-256-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charged-256-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charged-256-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charon-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charon-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charon-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charon-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/charon-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chela_light-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chela_light-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chela_light-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chela_light-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chela_light-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chlordane-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chlordane-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chlordane-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chlordane-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/chlordane-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clarity-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clarity-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clarity-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clarity-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clarity-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cleanphp-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cleanphp-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cleanphp-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cleanphp-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cleanphp-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cloudy-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cloudy-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cloudy-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cloudy-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cloudy-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clue-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clue-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clue-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clue-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/clue-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/codeburn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/codeburn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/codeburn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/codeburn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/codeburn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/coffee-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/coffee-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/coffee-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/coffee-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/coffee-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorer-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorer-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorer-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorer-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorer-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful256-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful256-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful256-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful256-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorful256-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorscheme_template-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorscheme_template-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorscheme_template-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorscheme_template-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorscheme_template-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorzone-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorzone-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorzone-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorzone-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/colorzone-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/contrasty-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/contrasty-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/contrasty-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/contrasty-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/contrasty-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cool-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cool-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cool-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cool-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cool-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corporation-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corporation-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corporation-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corporation-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/corporation-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/crt-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/crt-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/crt-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/crt-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/crt-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cthulhian-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cthulhian-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cthulhian-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cthulhian-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/cthulhian-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/custom-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/custom-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/custom-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/custom-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/custom-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dante-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dante-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dante-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dante-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dante-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkZ-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkZ-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkZ-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkZ-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkZ-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblack-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblack-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblack-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblack-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblack-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue2-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue2-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue2-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue2-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkblue2-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkbone-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkbone-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkbone-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkbone-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkbone-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkburn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkburn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkburn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkburn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkburn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdevel-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdevel-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdevel-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdevel-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdevel-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdot-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdot-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdot-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdot-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkdot-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkeclipse-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkeclipse-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkeclipse-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkeclipse-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkeclipse-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darker-robin-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darker-robin-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darker-robin-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darker-robin-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darker-robin-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkerdesert-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkerdesert-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkerdesert-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkerdesert-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkerdesert-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkocean-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkocean-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkocean-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkocean-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkocean-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkrobot-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkrobot-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkrobot-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkrobot-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkrobot-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkslategray-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkslategray-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkslategray-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkslategray-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkslategray-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkspectrum-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkspectrum-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkspectrum-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkspectrum-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkspectrum-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darktango-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darktango-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darktango-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darktango-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darktango-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkzen-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkzen-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkzen-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkzen-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/darkzen-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dawn-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dawn-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dawn-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dawn-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dawn-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/default-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/default-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/default-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/default-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/default-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delek-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delek-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delek-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delek-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delek-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delphi-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delphi-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delphi-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delphi-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/delphi-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/denim-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/denim-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/denim-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/denim-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/denim-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/derefined-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/derefined-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/derefined-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/derefined-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/derefined-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert256-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert256-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert256-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert256-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desert256-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertEx-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertEx-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertEx-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertEx-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertEx-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedocean-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedocean-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedocean-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedocean-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedocean-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedoceanburnt-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedoceanburnt-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedoceanburnt-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedoceanburnt-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/desertedoceanburnt-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/deveiate-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/deveiate-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/deveiate-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/deveiate-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/deveiate-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/developer-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/developer-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/developer-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/developer-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/developer-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/django-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/django-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/django-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/django-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/django-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doorhinge-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doorhinge-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doorhinge-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doorhinge-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doorhinge-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doriath-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doriath-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doriath-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doriath-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/doriath-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dual-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dual-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dual-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dual-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dual-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dusk-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dusk-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dusk-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dusk-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dusk-tex.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dw_blue-c.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dw_blue-html.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dw_blue-java.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dw_blue-pl.html
wget http://vimcolorschemetest.googlecode.com/svn/html/dw_blue-tex.html
