#!/bin/bash

wget http://vimcolorschemetest.googlecode.com/svn/colors/256-jungle.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/3dglasses.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Black.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/BlackSea.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Blue2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/BusyBee.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ChocolateLiquor.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ChocolatePapaya.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Dark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Dark2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DarkDefault.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DevC++.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Dim.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Dim2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimBlue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimGreen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimGreens.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimGrey.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimRed.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/DimSlate.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Green.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Light.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/LightDefault.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/LightDefaultGrey.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/LightTan.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/LightYellow.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/MountainDew.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/PapayaWhip.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Red.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/Slate.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/White2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/adam.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/adaryn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/adobe.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/adrian.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/advantage.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/af.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/aiseered.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/anotherdark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ansi_blows.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/aqua.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ashen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/asmanian2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/asmanian_blood.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/asmdev.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/asmdev2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/astronaut.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/asu1dark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/automation.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/autumn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/autumn2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/autumnleaf.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bandit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/basic.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bayQua.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/baycomb.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/beachcomber.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/beauty256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bensday.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/billw.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/biogoo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/black_angus.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blackbeauty.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blackboard.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blackdust.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blacklight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blink.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bluegreen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blueprint.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bluez.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/blugrine.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bmichaelsen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bog.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/borland.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/breeze.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/brookstream.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/brown.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/buttercream.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/bw.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/c.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/c16gui.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/calmar256-dark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/calmar256-light.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/camo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/campfire.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/candy.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/candycode.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/caramel.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/carrot.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/carvedwood.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/carvedwoodcool.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/charged-256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/charon.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/chela_light.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/chlordane.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/clarity.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/cleanphp.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/cloudy.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/clue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/codeburn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/coffee.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/colorer.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/colorful.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/colorful256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/colorscheme_template.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/colorzone.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/contrasty.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/cool.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/corn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/corporation.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/crt.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/cthulhian.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/custom.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dante.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkZ.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkblack.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkblue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkblue2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkbone.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkburn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkdevel.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkdot.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkeclipse.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darker-robin.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkerdesert.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkocean.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkrobot.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkslategray.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkspectrum.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darktango.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/darkzen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dawn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/default.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/delek.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/delphi.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/denim.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/derefined.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/desert.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/desert256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/desertEx.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/desertedocean.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/desertedoceanburnt.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/deveiate.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/developer.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/django.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/doorhinge.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/doriath.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dual.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dusk.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_blue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_cyan.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_green.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_orange.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_purple.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_red.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/dw_yellow.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/earendel.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/earth.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/earthburn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/eclipse.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/eclm_wombat.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/edo_sea.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ekvoli.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/elflord.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/elise.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/elisex.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/emacs.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/enzyme.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/evening.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/far.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fine_blue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fnaqevan.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fog.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/freya.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fruidle.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fruit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/fruity.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/gardener.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/gentooish.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/gobo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/golden.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/google.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/gor.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/gothic.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/grape.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/grayorange.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/graywh.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/greens.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/greenvision.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/greyblue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/guardian.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/guepardo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/h80.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/habiLight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/herald.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhazure.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdblue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdcyan.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdgray.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdgreen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdmagenta.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdred.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhdyellow.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhorange.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhpink.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhspring.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhteal.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/hhviolet.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ibmedit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/icansee.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/impact.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/impactG.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/industrial.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/inkpot.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ironman.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/jammy.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/jellybeans.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/jhdark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/jhlight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kalt.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kaltex.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kate.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kellys.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/khaki.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kib_darktango.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/kib_plastic.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/koehler.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lanzarotta.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lazarus.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/leo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/less.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lettuce.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lightcolors.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lilac.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lilydjwg_dark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lilydjwg_green.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lingodirector.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/literal_tango.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/louver.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/lucius.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/manxome.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/marklar.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/maroloccio.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/maroloccio2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/maroloccio3.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/mars.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/martin_krischik.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/matrix.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/mellow.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/metacosm.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/midnight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/midnight2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/miko.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/mint.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/mod_tcsoft.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/molokai.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/montz.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/moria.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/morning.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/motus.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/mud.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/murphy.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/native.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nature.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/navajo-night.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/navajo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nedit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nedit2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/neon.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/neverness.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nicotine.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/night.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightVision.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/night_vision.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightflight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightflight2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightshade.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightshade_print.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightshimmer.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightsky.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nightwish.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/no_quarter.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/northland.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/northsky.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/norwaytoday.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nour.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/nuvola.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/oceanblack.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/oceanblack256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/oceandeep.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/oceanlight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/olive.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/osx_like.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pablo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pacific.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/paintbox.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/peachpuff.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/peaksea.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/peppers.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/phphaxor.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/phpx.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pink.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pleasant.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/potts.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/print_bw.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/prmths.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/professional.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/proton.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ps_color.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pspad.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/putty.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/pyte.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/python.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/quagmire.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/railscasts.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_autumn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_breeze.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_fine_blue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_fruit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_neon.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_night.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rainbow_sea.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rastafari.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rcg_gui.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rcg_term.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rdark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/redblack.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/redstring.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/refactor.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/relaxedgreen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/reliable.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/reloaded.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/revolutions.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/robinhood.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/ron.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/rootwater.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sand.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/satori.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/scite.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sea.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sean.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/seashell.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/seoul.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/settlemyer.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sf.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/shine.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/shobogenzo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sienna.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/sift.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/silent.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/simple256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/simple_b.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/simpleandfriendly.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/simplewhite.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/skittles_dark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/slate2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/smp.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/softblue.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/softlight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/soruby.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/soso.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/spectro.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/spiderhawk.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/spring.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/stingray.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/summerfruit.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/summerfruit256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/surveyor.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/symfony.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/synic.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tabula.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tango-desert.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tango-morning.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tango.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tango2.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/taqua.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tcsoft.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/telstar.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tetragrammaton.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/textmate16.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/thegoodluck.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/thestars.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tibet.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tidy.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tolerable.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tomatosoup.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/toothpik.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/torte.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/transparent.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/trivial256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/turbo.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/tutticolori.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/twilight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/two2tango.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/umber-green.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/understated.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vanzan_color.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vc.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vcbc.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vexorian.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vibrantink.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vividchalk.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vj.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/void.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/vylight.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wargrey.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/warm_grey.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/watermark.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/white.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/whitedust.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/widower.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/win9xblueback.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/winter.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wintersday.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wombat.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wombat256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wood.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/wuye.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/xemacs.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/xian.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/xoria256.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/xterm16.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/yeller.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/zellner.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/zen.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/zenburn.vim
wget http://vimcolorschemetest.googlecode.com/svn/colors/zmrok.vim

